
sudo: false

language: java

install: true

os: linux
dist: trusty
jdk: oraclejdk8


cache:
  directories:
    - "$HOME/.cache"
script: ./mvnw clean install


jobs:
  include:
    - stage: Test
      script: ./mvnw clean test

#deploy:
#  provider: script
#  script: "mvn cobertura:cobertura & mvn deploy"
#  skip_cleanup: true
#  on:
#    tags: true

notifications:
  email:
    recipients:
      - sedat.kilinc@attempto.eu
    on_success: change
    on_failure: always